<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Grow.Infrastructure.Cqrs\Grow.Infrastructure.Cqrs.csproj" />
	<ProjectReference Include="..\Grow.Commons\Grow.Commons.csproj" />
  </ItemGroup>

</Project>
