<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>ee0c6da9-d328-4c95-b7e4-f725eccc5e7a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.7.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Grow.Commons\Grow.Commons.csproj" />
    <ProjectReference Include="..\Grow.Domain\Grow.Domain.csproj" />
    <ProjectReference Include="..\Grow.Infrastructure.Database\Grow.Infrastructure.Database.csproj" />
  </ItemGroup>

</Project>
